// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKssOVswkOg1Xm5dnOTMtaZChYrCg0Sn0',
    appId: '1:580286755795:web:1cf63d931ad255e5fe7526',
    messagingSenderId: '580286755795',
    projectId: 'fruit-hub-be7cf',
    authDomain: 'fruit-hub-be7cf.firebaseapp.com',
    storageBucket: 'fruit-hub-be7cf.firebasestorage.app',
    measurementId: 'G-6ZBY34YJC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAimmgbqy8EFeKjmtRzBLlw23ArZHdHxUo',
    appId: '1:580286755795:android:478fe216b5df1b56fe7526',
    messagingSenderId: '580286755795',
    projectId: 'fruit-hub-be7cf',
    storageBucket: 'fruit-hub-be7cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVfas9zFdEMUNENpHHcZLFdi5gZYBdO5M',
    appId: '1:580286755795:ios:7fd7dd3e88210367fe7526',
    messagingSenderId: '580286755795',
    projectId: 'fruit-hub-be7cf',
    storageBucket: 'fruit-hub-be7cf.firebasestorage.app',
    iosBundleId: 'com.example.fruits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVfas9zFdEMUNENpHHcZLFdi5gZYBdO5M',
    appId: '1:580286755795:ios:7fd7dd3e88210367fe7526',
    messagingSenderId: '580286755795',
    projectId: 'fruit-hub-be7cf',
    storageBucket: 'fruit-hub-be7cf.firebasestorage.app',
    iosBundleId: 'com.example.fruits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKssOVswkOg1Xm5dnOTMtaZChYrCg0Sn0',
    appId: '1:580286755795:web:cdc92991bc200af8fe7526',
    messagingSenderId: '580286755795',
    projectId: 'fruit-hub-be7cf',
    authDomain: 'fruit-hub-be7cf.firebaseapp.com',
    storageBucket: 'fruit-hub-be7cf.firebasestorage.app',
    measurementId: 'G-0ZE6VGNP79',
  );
}
